appium.server.url=http://127.0.0.1:4723
device.name=Pixel 9 API Baklava
platform.name=Android
app.package=com.alfabank.qapp
app.activity=.presentation.MainActivity
app=/Users/ivan/StudioProjects/qa-mobile/app/build/outputs/apk/debug/app-debug.apk
automation.name=UiAutomator2
new.command.timeout=60